### ISSUE TITLE
Рубежный контроль №1 (осень 2020)

### ISSUE THREAD

**Issue by Vlhub** [AndreiAvinov/MeteorMap#3]
Рекомендую:
- разместить аннотацию в reports/ann.md
- разместить в репозитории ТЗ (папка reports/tz.docx)
- приступить к формированию отчета (папка reports/ot.docx)

**Comment by AndreiAvinov** [comment]
1e5d75fcd5b73fdf37fa8ca32da767ba5dedcf71
